### ISSUE TITLE
Bugged Damage Manager

### ISSUE THREAD

**Issue by Tekuuze** [Stevemmmmmm/The-Blue-Hats-Server#2]
When I hit somebody normally, it does the normal amount of damage. However, if the opponent for example has Critically Funky 3 on their pants, the damage is 0.500HP, compared to the supposed 1.803HP

**Comment by TheRealStevemmmmm** [comment]
I am aware of the incorrect damage calculations from the DamageManager. This is mostly because of the iron pants calculation I had to use to try to make leathers pants to iron pants, because you can not add the armor points NBT attribute for any Minecraft version before 1.9. Eventually, I will upgrade the project spigot level to something around 1.12.2 with ViaVersion and resolve the issue.
